# try exception in python programming 

marks = [45, 34, 56, 78, 76]
try:
    passMarks = []
    for x in marks:
        if(x >= 50):
            passMarks.append(x)
    print(passMarks)

except:
    print('Error heppen in your code!')

finally:
    print('You have done the work')

print("Python is very smart programming language")
print('\n')

try:
    passMarks = []
    for x in age:
        if(x >= 50):
            passMarks.append(x)
    print(passMarks)

except:
    print('Error heppen in your code!')

finally:
    print('You have done the work')

print("Python is very smart programming language")